#!/bin/bash

while getopts "d" option
do
  case $option in
    d) debug="--enable-debug";;
  esac
done

./configure \
    --prefix=$PHP_HOME \
    --enable-mbstring \
    --enable-intl \
    --enable-mysqlnd \
    --enable-pdo \
    --enable-exif \
    --enable-mbregex \
    --enable-ftp \
    --enable-opcache \
    $debug \
    --with-gd \
    --with-png-dir=/var/www \
    --with-jpeg-dir=/var/www \
    --with-apxs2=/usr/bin/apxs \
    --with-gettext \
    --with-mysqli \
    --with-pdo-mysql \
    --with-openssl \
    --with-xsl \
    --with-curl \
    --with-mcrypt \
    --with-tidy \
    --with-zlib \
    --with-config-file-path=$PHP_HOME/conf.d \

# --with-xdiff
